node_js:
  - "8.0.0"

install:
  - npm install -g https://github.com/INCF/bids-validator.git

script:
  - |
    rc=0;
    for i in $(ls -d */);
    do
      echo "Validating dataset" $i
      bids-validator ${i%%/} --ignoreNiftiHeaders --bep010 || rc=$?
    done
    exit $rc;
